import abacinematica from "../assets/aba-cinematica.png";
import abacos from "../assets/aba-cos.png";
import abaeletricidade from "../assets/aba-eletricidade.png";
import abaequacoes from "../assets/aba-equacoes.png";
import abageometria from "../assets/aba-geometria.png";
import abahome from "../assets/aba-home.png";
import abamath from "../assets/aba-math.png";
import abaoptica from "../assets/aba-optica.png";
import abaperfil from "../assets/aba-perfil.png";
import abatermodinamica from "../assets/aba-termodinamica.png";
import logo from "../assets/logo.png";
import logo2 from "../assets/logo2.png";
import logo3 from "../assets/logo3.png";
import seta from "../assets/seta.png";
import cos from "../assets/cos.png";
import eletric from "../assets/eletric.png";
import func from "../assets/func.png";
import geometric from "../assets/geometric.png";
import globo from "../assets/globo.png";
import integral from "../assets/integral.png";
import ligth from "../assets/ligth.png";
import thermic from "../assets/thermic.png";

export default { logo, logo2, logo3, seta, abahome, abacinematica, abamath, abaperfil, abaequacoes, abageometria, abacos, abaeletricidade, abatermodinamica, abaoptica, cos, eletric, func, geometric, globo, integral, ligth, thermic };